# Importing libraries

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [11]:
tf.__version__

'2.16.2'

# Data Preprocessing

### 1. Importing Dataset

In [66]:
dataset = pd.read_csv("Churn_Modelling.csv")
dataset

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [67]:
dataset.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

### 2. Deleting unwanted rows

In [68]:
dataset.drop(columns=['RowNumber', 'CustomerId', 'Surname'], axis=1, inplace=True)
dataset

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

### 3. Encoding Categorical Variables

In [69]:
dataset.dtypes

CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [70]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_variables = ['Geography', 'Gender']
le = LabelEncoder()
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), ['Geography'])])

dataset['Gender'] = le.fit_transform(dataset['Gender'])
dataset['Geography'] = ct.fit_transform(dataset)

In [71]:
print(type(dataset))

<class 'pandas.core.frame.DataFrame'>

In [72]:
dataset

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,1.0,0,42,2,0.00,1,1,1,101348.88,1
1,608,0.0,0,41,1,83807.86,1,0,1,112542.58,0
2,502,1.0,0,42,8,159660.80,3,1,0,113931.57,1
3,699,1.0,0,39,1,0.00,2,0,0,93826.63,0
4,850,0.0,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1.0,1,39,5,0.00,2,1,0,96270.64,0
9996,516,1.0,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,1.0,0,36,7,0.00,1,0,1,42085.58,1
9998,772,0.0,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,1.0,0,28,4,130142.79,1,1,0,38190.78,0

### 4. Splitting dataset into training and testing sets

In [74]:
from sklearn.model_selection import train_test_split

X = dataset.drop('Exited', axis=1)
y = dataset['Exited']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
len(X_train), len(X_test), len(y_train), len(y_test)

(8000, 2000, 8000, 2000)

### 5. Feature Scaling

In [76]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

# Builing ANN

### 1. Initializing the ANN

In [77]:
ann = tf.keras.models.Sequential()

### 2. Adding input layer and 1st hidden layer

In [78]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### 3. Adding the 2nd hidden layer

In [79]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### 4. Adding the output layer

for binary classification -> `activation=sigmoid`

for non-binary classification -> `activation=soft-max`

In [80]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Training the ANN

### 1. Compiling the ANN

for binary classification -> `loss=binary_crossentropy`

for non-binary classification -> `loss=categorical_crossentropy`

In [83]:
ann.compile(optimizer='adam', metrics=['accuracy'], loss='binary_crossentropy')

### 2. Training the ANN on dataset

In [84]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 231us/step - accuracy: 0.8632 - loss: 0.3388
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 208us/step - accuracy: 0.8527 - loss: 0.3477
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 210us/step - accuracy: 0.8553 - loss: 0.3495
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 212us/step - accuracy: 0.8527 - loss: 0.3511
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 214us/step - accuracy: 0.8664 - loss: 0.3328
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 219us/step - accuracy: 0.8619 - loss: 0.3390
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 222us/step - accuracy: 0.8574 - loss: 0.3471
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 221us/step - accuracy: 0.8590 - loss: 0.3429
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 216us/step - accuracy: 0.8621 - loss: 0.3447
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 216us/step - accuracy: 0.8664 - loss: 0.3288
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 218us/step - accuracy: 0.8623 - loss: 0.3340
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 218us/step - accuracy: 0.8570 - loss: 0.3445
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 222us/step - accuracy: 0.8670 - loss: 0.3313
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 221us/step - accuracy: 0.8537 - loss: 0.3456
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 218us/step - accuracy: 0.8598 - loss: 0.3380
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 220us/step - accuracy: 0.8604 - loss: 0.3378
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 219us/step - accuracy: 0.8538 - loss: 0.3474
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 222us/step - accuracy: 0.8541 - loss: 0.3495
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 351us/step - accuracy: 0.8584 - loss: 0.3430
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 220us/step - accuracy: 0.8598 - loss: 0.3407
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 221us/step - accuracy: 0.8549 - loss: 0.3432
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 222us/step - accuracy: 0.8534 - loss: 0.3487
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 222us/step - accuracy: 0.8529 - loss: 0.3468
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 216us/step - accuracy: 0.8535 - loss: 0.3497
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 218us/step - accuracy: 0.8551 - loss: 0.3560
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 220us/step - accuracy: 0.8535 - loss: 0.3497
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 220us/step - accuracy: 0.8582 - loss: 0.3411
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 226us/step - accuracy: 0.8576 - loss: 0.3459
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 222us/step - accuracy: 0.8592 - loss: 0.3418
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 223us/step - accuracy: 0.8563 - loss: 0.3526
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 226us/step - accuracy: 0.8555 - loss: 0.3452
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 224us/step - accuracy: 0.8571 - loss: 0.3482
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 228us/step - accuracy: 0.8603 - loss: 0.3402
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 222us/step - accuracy: 0.8567 - loss: 0.3372
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 223us/step - accuracy: 0.8519 - loss: 0.3533
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 230us/step - accuracy: 0.8655 - loss: 0.3317
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 223us/step - accuracy: 0.8567 - loss: 0.3481
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 221us/step - accuracy: 0.8565 - loss: 0.3494
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 223us/step - accuracy: 0.8644 - loss: 0.3382
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 220us/step - accuracy: 0.8577 - loss: 0.3409
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 215us/step - accuracy: 0.8583 - loss: 0.3404
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 221us/step - accuracy: 0.8632 - loss: 0.3348
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 218us/step - accuracy: 0.8559 - loss: 0.3406
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 221us/step - accuracy: 0.8576 - loss: 0.3421
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 218us/step - accuracy: 0.8542 - loss: 0.3442
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 218us/step - accuracy: 0.8601 - loss: 0.3349
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 219us/step - accuracy: 0.8596 - loss: 0.3369
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 379us/step - accuracy: 0.8619 - loss: 0.3311
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 219us/step - accuracy: 0.8585 - loss: 0.3454
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 217us/step - accuracy: 0.8666 - loss: 0.3325
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 219us/step - accuracy: 0.8627 - loss: 0.3342
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 220us/step - accuracy: 0.8552 - loss: 0.3397
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 223us/step - accuracy: 0.8548 - loss: 0.3485
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 230us/step - accuracy: 0.8598 - loss: 0.3364
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 218us/step - accuracy: 0.8550 - loss: 0.3388
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 220us/step - accuracy: 0.8651 - loss: 0.3368
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 218us/step - accuracy: 0.8553 - loss: 0.3510
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 219us/step - accuracy: 0.8593 - loss: 0.3352
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 218us/step - accuracy: 0.8583 - loss: 0.3478
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 218us/step - accuracy: 0.8568 - loss: 0.3379
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 216us/step - accuracy: 0.8633 - loss: 0.3360
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 214us/step - accuracy: 0.8546 - loss: 0.3459
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 216us/step - accuracy: 0.8508 - loss: 0.3509
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 217us/step - accuracy: 0.8603 - loss: 0.3392
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 215us/step - accuracy: 0.8572 - loss: 0.3454
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 217us/step - accuracy: 0.8539 - loss: 0.3455
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 215us/step - accuracy: 0.8593 - loss: 0.3437
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 215us/step - accuracy: 0.8650 - loss: 0.3323
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - accuracy: 0.8639 - loss: 0.3333
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 218us/step - accuracy: 0.8636 - loss: 0.3298
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 216us/step - accuracy: 0.8561 - loss: 0.3473
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 216us/step - accuracy: 0.8579 - loss: 0.3303
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 219us/step - accuracy: 0.8627 - loss: 0.3343
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 220us/step - accuracy: 0.8558 - loss: 0.3455
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 223us/step - accuracy: 0.8632 - loss: 0.3375
Epoch 76/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 222us/step - accuracy: 0.8605 - loss: 0.3371
Epoch 77/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 220us/step - accuracy: 0.8654 - loss: 0.3320
Epoch 78/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 218us/step - accuracy: 0.8622 - loss: 0.3466
Epoch 79/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 219us/step - accuracy: 0.8589 - loss: 0.3435
Epoch 80/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 221us/step - accuracy: 0.8576 - loss: 0.3431
Epoch 81/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 215us/step - accuracy: 0.8571 - loss: 0.3458
Epoch 82/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 220us/step - accuracy: 0.8592 - loss: 0.3440
Epoch 83/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 219us/step - accuracy: 0.8612 - loss: 0.3421
Epoch 84/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 223us/step - accuracy: 0.8604 - loss: 0.3443
Epoch 85/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 219us/step - accuracy: 0.8577 - loss: 0.3431
Epoch 86/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 338us/step - accuracy: 0.8619 - loss: 0.3377
Epoch 87/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 222us/step - accuracy: 0.8591 - loss: 0.3367
Epoch 88/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 219us/step - accuracy: 0.8594 - loss: 0.3389
Epoch 89/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 219us/step - accuracy: 0.8550 - loss: 0.3432
Epoch 90/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 221us/step - accuracy: 0.8575 - loss: 0.3412
Epoch 91/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 220us/step - accuracy: 0.8551 - loss: 0.3470
Epoch 92/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 217us/step - accuracy: 0.8603 - loss: 0.3382
Epoch 93/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 217us/step - accuracy: 0.8591 - loss: 0.3431
Epoch 94/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 219us/step - accuracy: 0.8544 - loss: 0.3450
Epoch 95/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 219us/step - accuracy: 0.8634 - loss: 0.3409
Epoch 96/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 220us/step - accuracy: 0.8627 - loss: 0.3319
Epoch 97/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 221us/step - accuracy: 0.8670 - loss: 0.3279
Epoch 98/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 221us/step - accuracy: 0.8534 - loss: 0.3455
Epoch 99/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 218us/step - accuracy: 0.8534 - loss: 0.3477
Epoch 100/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 363us/step - accuracy: 0.8652 - loss: 0.3350

# Making Predictions and evaluating the model

In [92]:
from sklearn.metrics import accuracy_score, confusion_matrix

y_preds = ann.predict(X_test)
y_preds = (y_preds > 0.5)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 232us/step

In [95]:
cm = confusion_matrix(y_test, y_preds)
print(cm)
accuracy_score(y_test, y_preds)

[[1524   71]
 [ 216  189]]

0.8565